### ISSUE TITLE
Wonambi - startup TypeError on Windows

### ISSUE THREAD

**Issue by dpkoller** [wonambi-python/wonambi#11]
Hi, thanks for the great piece of software. I've been using it for sleep scoring and spindle detection on MacOS, which has been working like a charm. Recently I had to move to Windows. Currently I'm using the following setup:

64-bit Windows 7 
Anaconda 4.5.9.
Python 3.6.5

after setting up wonambi according to the installation [guide](https://wonambi-python.github.io/installation.html) I have tried to startup wonambi, which resulted in the following error:

```
c:\users\anaconda\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
11:39:16  WONAMBI v5.32
qt.qpa.fonts: Unable to open default EUDC font: "C:\\windows\\FONTS\\EUDC.TTE"
Traceback (most recent call last):
  File "c:\users\anaconda\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\anaconda\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\anaconda\anaconda3\Scripts\wonambi.exe\__main__.py", line 9, in <module>
  File "c:\users\anaconda\anaconda3\lib\site-packages\wonambi\scroll_data.py", line 305, in main
    q = MainWindow()
  File "c:\users\anaconda\anaconda3\lib\site-packages\wonambi\scroll_data.py", line 67, in __init__
    self.create_widgets()
  File "c:\users\anaconda\anaconda3\lib\site-packages\wonambi\widgets\creation.py", line 49, in create_widgets
    MAIN.traces = Traces(MAIN)
  File "c:\users\anaconda\anaconda3\lib\site-packages\wonambi\widgets\traces.py", line 175, in __init__
    self.config = ConfigTraces(self.parent.overview.update_position)
  File "c:\users\anaconda\anaconda3\lib\site-packages\wonambi\widgets\traces.py", line 67, in __init__
    super().__init__('traces', update_widget)
  File "c:\users\anaconda\anaconda3\lib\site-packages\wonambi\widgets\settings.py", line 206, in __init__
    self.value = self.create_values(value_names)
  File "c:\users\anaconda\anaconda3\lib\site-packages\wonambi\widgets\settings.py", line 228, in create_values
    output[value_name] = read_settings(self.widget, value_name)
  File "c:\users\anaconda\anaconda3\lib\site-packages\wonambi\widgets\settings.py", line 337, in read_settings
    val = settings.value(setting_name, default_value, type=default_type)
TypeError: unable to convert a QVariant of type 10 to a QMetaType of type 2
```

So far I couldn't figure out how to resolve this error. Maybe this is a known issue on Windows?

**Comment by gpiantoni** [comment]
Sorry for the late reply. I wonder if it's an error in the settings file. 

Can you try: ``wonambi --reset`` ?
(this will delete your saved settings but this doesn't seem a problem on your first start).

We run wonambi on Windows regularly. This is not a known issue but we should be able to debug it.

**Comment by dpkoller** [comment]
Thanks for your reply. Running `wonambi --reset` results in the same error output. I have re-installed anaconda and wonambi but it did not help to resolve the issue.

Do you have any other suggestions?
